BEGIN TRANSACTION;
CREATE TABLE shuttle (
	`sgw_loy_moth`	TEXT,
	`sgw_loy_fri`	TEXT,
    `loy_sgw_moth`  TEXT,
    `loy_sgw_fri`   TEXT
);
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','-','07:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('07:45','07:45','07:45','07:45');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('08:05','-','08:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('08:20','08:20','08:20','08:20');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('08:35','-','08:35','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('08:55','08:55','08:55','08:55');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('09:10','-','09:10','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('09:30','9:30','09:30','09:30');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('09:45','-','09:45','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('10:05','10:05','-','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('10:20','-','10:20','10:20');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','-','10:35','10:35');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('10:55','10:55','10:55','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('11:10','11:10','11:10','11:10');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','-','11:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('11:45','11:45','-','11:45');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('12:00','-','12:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','12:20','-','12:20');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('12:30','-','12:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','12:55','-','12:55');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('13:00','-','13:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('13:30','13:30','13:30','13:30');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('14:00','-','14:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','14:05','-','14:05');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('14:30','-','14:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','14:40','-','14:40');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('15:00','-','15:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','15:15','-','15:15');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('15:30','-','15:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','15:50','-','15:50');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('16:00','-','16:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','16:25','-','16:25');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('16:30','-','16:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('17:00','-','17:00','17:00');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','17:15','-','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('17:30','17:30','17:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('18:00','-','18:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','18:05','-','18:05');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('18:30','-','18:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','18:40','-','18:40');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('19:00','-','19:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','19:15','-','19:15');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('19:30','-','19:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','19:50','-','19:50');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('20:00','-','20:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('20:15','-','-','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('20:30','-','20:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('21:00','-','21:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('21:25','-','-','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('-','-','21:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('21:45','-','-','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('22:00','-','22:00','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('22:30','-','22:30','-');
INSERT INTO `shuttle` (sgw_loy_moth,sgw_loy_fri,loy_sgw_moth,loy_sgw_fri) VALUES ('23:00','-','23:00','-');
COMMIT;
